### ISSUE TITLE
ImportError: cannot import name 'tokenization_bert'

### ISSUE THREAD

**Issue by ady-yu** [kathrynchapman/QA_project#1]
when I run the code,i meet this error.Can you tell me how to solve it?
Traceback (most recent call last):
  File "main_qa_script.py", line 26, in <module>
    from pt_cqa_supports import *
  File "/home/fish/projects/QA_project/scripts/pt_cqa_supports.py", line 16, in <module>
    from transformers import BertTokenizer, tokenization_bert
ImportError: cannot import name 'tokenization_bert'

**Comment by kathrynchapman** [comment]
Hmm, it seems probably the wrong Transformers version is installed. Did you create a new environment using the requirements.txt file?

**Comment by ady-yu** [comment]
> Hmm, it seems probably the wrong Transformers version is installed. Did you create a new environment using the requirements.txt file?

Oh,no.I don't use the requirements.txt 's environment. Is the requirements.txt refers the Transformers version? I dont find the Transformers version

**Comment by kathrynchapman** [comment]
I'd recommend trying transformers=2.4.1. We implemented this paper in PyTorch from the original TF code, but were unable to replicate their results. So just know that, this this code doesn't give the same results as the original paper's.

**Comment by ady-yu** [comment]
> =2.4.1

Thanks！！！！This version works.

**Comment by ady-yu** [comment]
> I'd recommend trying transformers=2.4.1. We implemented this paper in PyTorch from the original TF code, but were unable to replicate their results. So just know that, this this code doesn't give the same results as the original paper's.

I wonder what the result you get when implementing the code. Thanks
